---
title: "Course Exercise #3"
author: "Rodrigo Zamith"
output:
  html_document:
    toc: yes
    toc_depth: 5
    toc_float: true
    code_folding: show
    df_print: paged
    theme: spacelab
    highlight: pygment
---

### Introduction

The purpose of this assignment is to demonstrate your ability to write a short news story based on your analysis of a dataset, and to then identify human sources who could later strengthen that story. You may work with *up to three classmates* on this assignment---if you do so, please note your classmates in the `author` part of your R Notebook header (e.g., `author: "Rodrigo Zamith (with Bukayo Saka, Kieran Tierney, and Emile Smith Rowe)"`).

You will be submitting an R Notebook (**both** the `.Rmd` and `.html` files) that answers the questions at the bottom of this page.

-----

### The Data

The primary dataset you will be working with includes [Paycheck Protection Program loan data](https://home.treasury.gov/policy-issues/cares-act/assistance-for-small-businesses/sba-paycheck-protection-program-loan-level-data) covering all loans up until August 8, 2020. If you are unfamiliar with the PPP, [Wikipedia might help](https://en.wikipedia.org/wiki/Paycheck_Protection_Program). [This short document](https://www.sba.gov/sites/default/files/2020-08/PPP%20Loan%20Data%20-%20Key%20Aspects%2008212020-508.pdf) from the Small Business Administration also includes useful context for these data.

The full dataset published by the U.S. Department of the Treasury covers all 50 states, but to keep the file size manageable, _I have only included data for Massachusetts_. Additionally, the Department of the Treasury splits these data into two separate datasets: one for loans under $150,000 (which includes an exact amount, which you can find under `LoanAmount`) and one for loans above $150,000 (which _only includes a general range_, which you can find under `LoanRange`). The CSV file you will be using for this assignment is a combination of those two datasets, with some additional clean-up work to save you time.

You will also be working with two additional datasets. The first is a translation dataset that maps [North American Industry Classification System](https://en.wikipedia.org/wiki/North_American_Industry_Classification_System) codes into industry names, which would make it easier for you to examine the distribution of loans by industry. The second is a translation dataset that helps standardize some of the sloppy city names by adding a new variable (`CityStandardized`). I quickly performed this clean-up effort myself, and it may still have some mistakes---but it is certainly in better shape than the original SBA data, which simply relied on the applicants' mistake-riddled input.

You are welcome to combine these data with any other dataset that may prove useful to you.

-----

### Your Objective

Please answer the following questions through an R Notebook (please use [this template file](https://zamith.umasscreate.net/data/exercise_3_yourname.Rmd)):

1. Combine the `ppp_ma` data frame with the `naics_codes` and `city_standardized` data frames, so we have information about the different industries that received the loans and less-messy city names. _(2 points)_

&nbsp;

2. You have entered a time machine that takes you back to August 10, 2020. Your editor at the [_Daily Hampshire Gazette_](https://en.wikipedia.org/wiki/Daily_Hampshire_Gazette) has asked you to write a short story _about the Paycheck Protection Program and how those funds have been distributed_. Explore the dataset and come up with **five** interview questions **for these data**. Be sure to write out each question (try to orient the phrasing around _quantifiable things_ that you can observe in/evaluate through the dataset). Then, use R to answer the question and _write out a clear answer to your own question_. _(2 points each; 10 points total)_
    - Remember who your audience is here (_Gazette_ readers), as well as the context around that time period. Questions were being raised about who was getting money, whether it was being thoughtfully distributed, if the amounts were sufficient (or excessive), etc. You are welcome to use external resources (e.g., links to reports, articles, and other data _published before August 10_).

&nbsp;

3. Your editor has tasked you to write a **300-400 word news story** that incorporates the fruits of your analysis. You've been given full editorial autonomy for the final story angle (aspect of the issue the article focuses on). "You've been doing the digging, so you know the story best," the editor said. _(12 points)_
    - We have not yet covered newswriting yet, so I will not be grading the quality of **newswriting** too closely, though I expect the story to be grammatically sound. However, here are some tips to consider at this stage:
        - The lede, or introduction to the story, is typically no longer than a couple of sentences. It should either summarize the main points of the story or suck a reader in with a striking finding or anecdote. Do **not** write a novel.
        - Paragraphs in news stories are rarely longer than four sentences. In fact, many are just one to two sentences in length. News stories tend to have a fast pace to them and are designed to be easy to read. (In short, avoid long paragraphs.)
        - Sentences are typically short and simple. Take creative liberty when you have mastered the basics of a subject-verb-object formula (e.g., "The Centers for Disease Control and Prevention announced new social distancing guidelines on Monday."). Succinct writing is best.
        - Use _simple language_. You want your work to be accessible. Simplify any terms of art and assume your reader has a high school reading comprehension level.
        - Avoid the first-person for this story. Similarly, please do not write, "I decided to analyze the data to see what the infection rate was." Instead, just get to the answer: "According to data from the CDC, Florida's infection rate was ... ." Remember that this is a news story, not a lab report.
        - Source all claims/assertions in your story. Where did the information come from? (Links are great!)
        - Do not repeat information, or summarize the story at the end by repeating what has been written in preceding paragraphs. Find a conclusion that leaves the reader feeling satisfied.
        - You do **not** have to include every finding in your story. Focus on the most interesting stuff. Sometimes, less is more.

&nbsp;

4. Identify **two** interviewees who can add some expertise to this story. Recall that there are different forms of expertise, and the purpose of these individuals is to help contextualize the story and add a different layer to the analysis you have performed. For **each** interviewee, please provide the following information: _(3 points each; 6 points total)_
    - Their name, title/position, and the main (or most relevant) organization they work for.
    - Their contact information (e.g., a work phone number or e-mail address).
    - The URL to some page that offers details about them (e.g., biography page, personal website). If the source does not have a URL, please provide a short description that would help your editor ascertain their appropriateness for this piece.
    - A couple of sentences that details what you think they could add to your article. Please **be specific**. For example, maybe they've done some research that could help explain a specific finding you from your analysis, or they have some specific lived experience that would help contextualize the reporting.
    - Your **three** most important interview questions for _that specific human source_. Assume that you are conducting the interview over the phone, and that you've already established a rapport with them. Be sure to phrase your questions in a thoughtful way, per the advice from the lesson materials, and key them to the source's expertise.
    - **This semester, you will not have to conduct the actual interview. Just complete the information above.**
